const config = {
  links: {
    github: "https://github.com/SurenAt93/monaco-react",
  },

  notifications: {
    props: {
      anchorOrigin: { vertical: "top", horizontal: "right" },
      autoHideDuration: 2500,
    },
    defaultState: {
      isActive: false,
      message: "",
      variant: "info",
      opt: {},
    },
  },

  messages: {
    errorBoundary: {
      somethingWentWrong:
        "Oooops... Sorry, I guess, something went wrong. You can:",
      resetApp: "Press here to reset the application",
      openIssue: "Press here to open issue about it on GitHub",
    },
    invalidOptions:
      "Seems like options file is not a valid json, please double check it.",
  },

  urls: {
    octocatIcon: "/icons/octocat.png",
    themeModeIcon: "/icons/theme-mode.png",
    IEditorOptions:
      "https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditoroptions.html#acceptsuggestiononcommitcharacter",
  },

  defaultThemes: ["vs-dark", "light"],

  // supportedLanguages: [
  //   { id: 1, name: "apex" },
  //   { id: 2, name: "azcli" },
  //   { id: 3, name: "bat" },
  //   { id: 4, name: "c" },
  //   { id: 5, name: "clojure" },
  //   { id: 6, name: "coffeescript" },
  //   { id: 7, name: "cpp" },
  //   { id: 8, name: "csharp" },
  //   { id: 9, name: "csp" },
  //   { id: 10, name: "css" },
  //   { id: 11, name: "dockerfile" },
  //   { id: 12, name: "fsharp" },
  //   { id: 13, name: "go" },
  //   { id: 14, name: "graphql" },
  //   { id: 15, name: "handlebars" },
  //   { id: 16, name: "html" },
  //   { id: 17, name: "ini" },
  //   { id: 18, name: "java" },
  //   { id: 19, name: "javascript" },
  //   { id: 20, name: "json" },
  //   { id: 21, name: "kotlin" },
  //   { id: 22, name: "less" },
  //   { id: 23, name: "lua" },
  //   { id: 24, name: "markdown" },
  //   { id: 25, name: "msdax" },
  //   { id: 26, name: "mysql" },
  //   { id: 27, name: "objective-c" },
  //   { id: 28, name: "pascal" },
  //   { id: 29, name: "perl" },
  //   { id: 30, name: "pgsql" },
  //   { id: 31, name: "php" },
  //   { id: 32, name: "plaintext" },
  //   { id: 33, name: "postiats" },
  //   { id: 34, name: "powerquery" },
  //   { id: 35, name: "powershell" },
  //   { id: 36, name: "pug" },
  //   { id: 37, name: "python" },
  //   { id: 38, name: "r" },
  //   { id: 39, name: "razor" },
  //   { id: 40, name: "redis" },
  //   { id: 41, name: "redshift" },
  //   { id: 42, name: "ruby" },
  //   { id: 43, name: "rust" },
  //   { id: 44, name: "sb" },
  //   { id: 45, name: "scheme" },
  //   { id: 46, name: "scss" },
  //   { id: 47, name: "shell" },
  //   { id: 48, name: "sol" },
  //   { id: 49, name: "sql" },
  //   { id: 50, name: "st" },
  //   { id: 51, name: "swift" },
  //   { id: 52, name: "tcl" },
  //   { id: 53, name: "typescript" },
  //   { id: 54, name: "vb" },
  //   { id: 55, name: "xml" },
  //   { id: 56, name: "yaml" },
  // ],

  supportedLanguages: {
    45: { lang: "Assembly (NASM 2.14.02)", editor: "plaintext" },
    46: { lang: "Bash (5.0.0)", editor: "shell" },
    47: { lang: "Basic (FBC 1.07.1)", editor: "plaintext" },
    75: { lang: "C (Clang 7.0.1)", editor: "c" },
    76: { lang: "C++ (Clang 7.0.1)", editor: "cpp" },
    48: { lang: "C (GCC 7.4.0)", editor: "c" },
    52: { lang: "C++ (GCC 7.4.0)", editor: "cpp" },
    49: { lang: "C (GCC 8.3.0)", editor: "c" },
    53: { lang: "C++ (GCC 8.3.0)", editor: "cpp" },
    50: { lang: "C (GCC 9.2.0)", editor: "c" },
    54: { lang: "C++ (GCC 9.2.0)", editor: "cpp" },
    86: { lang: "Clojure (1.10.1)", editor: "clojure" },
    51: { lang: "C# (Mono 6.6.0.161)", editor: "csharp" },
    77: { lang: "COBOL (GnuCOBOL 2.2)", editor: "plaintext" },
    55: { lang: "Common Lisp (SBCL 2.0.0)", editor: "plaintext" },
    56: { lang: "D (DMD 2.089.1)", editor: "plaintext" },
    57: { lang: "Elixir (1.9.4)", editor: "plaintext" },
    58: { lang: "Erlang (OTP 22.2)", editor: "plaintext" },
    87: { lang: "F# (.NET Core SDK 3.1.202)", editor: "fsharp" },
    59: { lang: "Fortran (GFortran 9.2.0)", editor: "plaintext" },
    60: { lang: "Go (1.13.5)", editor: "go" },
    88: { lang: "Groovy (3.0.3)", editor: "plaintext" },
    61: { lang: "Haskell (GHC 8.8.1)", editor: "plaintext" },
    62: { lang: "Java (OpenJDK 13.0.1)", editor: "java" },
    63: { lang: "JavaScript (Node.js 12.14.0)", editor: "javascript" },
    78: { lang: "Kotlin (1.3.70)", editor: "kotlin" },
    64: { lang: "Lua (5.3.5)", editor: "lua" },
    79: { lang: "Objective-C (Clang 7.0.1)", editor: "objective-c" },
    65: { lang: "OCaml (4.09.0)", editor: "plaintext" },
    66: { lang: "Octave (5.1.0)", editor: "plaintext" },
    67: { lang: "Pascal (FPC 3.0.4)", editor: "pascal" },
    85: { lang: "Perl (5.28.1)", editor: "perl" },
    68: { lang: "PHP (7.4.1)", editor: "php" },
    43: { lang: "Plain Text", editor: "plaintext" },
    69: { lang: "Prolog (GNU Prolog 1.4.5)", editor: "plaintext" },
    70: { lang: "Python (2.7.17)", editor: "python" },
    71: { lang: "Python (3.8.1)", editor: "python" },
    80: { lang: "R (4.0.0)", editor: "r" },
    72: { lang: "Ruby (2.7.0)", editor: "ruby" },
    73: { lang: "Rust (1.40.0)", editor: "rust" },
    81: { lang: "Scala (2.13.2)", editor: "plaintext" },
    82: { lang: "SQL (SQLite 3.27.2)", editor: "sql" },
    83: { lang: "Swift (5.2.3)", editor: "swift" },
    74: { lang: "TypeScript (3.7.4)", editor: "typescript" },
    84: { lang: "Visual Basic.Net (vbnc 0.0.0.5943)", editor: "vb" },
  },
};

export default config;
